extends Node

func robot_phrases(language_data):
	#delete below
	var data_to_send = {
		"en":{"Game_name":"ShapeStylist",
		"saudacao":"Hello friend!",
		"frase_1":"My name is ",
		"possibilidade_nomes":"John",
		"possibilidade_nomes2":"Jose",
		"possibilidade_nomes3":"Jack",
		"possibilidade_nomes4":"Josefino",
		"possibilidade_nomes5":"Alberto",
		"possibilidade_nomes6":"Ronaldo",
		"possibilidade_nomes7":"Richard",
		"possibilidade_nomes8":"Kleyson",
		"possibilidade_nomes9":"Bot1231",
		"possibilidade_nomes10":"#312112",
		"possibilidade_nomes11":"Teofilo",
		"possibilidade_nomes12":"Blake",
		"frase_2":"I like ",
		"possibilidade_gostos":"Sports",
		"possibilidade_gostos2":"Art",
		"possibilidade_gostos3":"Rock",
		"possibilidade_gostos4":"Painting",
		"possibilidade_gostos5":"Sleeping",
		"frase_3":"This is the haircut I want",
		"largura":"width",
		"altura":"height",
		"area":"area",
		"placeholder_resposta":"answer here",
		"placeholder_unidade":"unit here",
		"texto_resultado":"The area is",
		"label_lados":"side",
		"desistir" : "Let's try again, from the beginning!",
		"ultima_frase":"I loved it!",
		"ultima_frase2":"It's awesome!",
		"ultima_frase3":"Really nice!",
		"ultima_frase4":"It's perfect!",
		"ultima_frase5":"I'm really happy",
		"ultima_frase6":"You made my day!",
		"acerto":"Excellent!",
		"valor_a_receber":"Haircut price",
		"erros_cometidos":"Mistakes made",
		"dinheiro_perdido":"Money lost",
		"lucro":"Profit",
		"dinheiro_fim_do_dia":"Earned money",
		"despesas":"Expenses",
		"comecar":"Start Game",
		"proximo":"Next client",
		"proximo_dia":"Next day",
		"satisfeitos":"Satisfied clients",
		"insatisfeitos":"New attempts",
		"erros":"Mistakes",
		"dinheiro_total":"All time earned", #########################################################
		"menu":"Menu",
		"carregar":"Load Game",
		"sair":"Quit Game"}, 
		
		"es":{"saudacao":"¡Hola amigo!",
		"frase_1":"Mi nombre es ", 
		"possibilidade_nomes":"John",
		"possibilidade_nomes2":"Jose",
		"possibilidade_nomes3":"Jack",
		"possibilidade_nomes4":"Josefino",
		"possibilidade_nomes5":"Alberto",
		"possibilidade_nomes6":"Ronaldo",
		"possibilidade_nomes7":"Richard",
		"possibilidade_nomes8":"Kleyson",
		"possibilidade_nomes9":"Bot1231",
		"possibilidade_nomes10":"#312112",
		"possibilidade_nomes11":"Teofilo",
		"possibilidade_nomes12":"Blake",
		"frase_2":"Me gusta ",
		"possibilidade_gostos":"Desportos",
		"possibilidade_gostos2":"Pintura",
		"possibilidade_gostos3":"Artes",
		"possibilidade_gostos4":"Rock",
		"possibilidade_gostos5":"Dormir",
		"frase_3":"Quiero este corte",
		"largura":"ancho",
		"altura":"altura",
		"area":"área",
		"placeholder_resposta":"responde aquí",
		"placeholder_unidade":"unidad aquí",
		"texto_resultado":"El área es",
		"label_lados":"lado",
		"desistir" : "No puedes ayudarme", #################################################
		"ultima_frase":"¡Yo amé!",
		"ultima_frase2":"¡Esta perfecto!",
		"ultima_frase3":"¡Muy bien!",
		"ultima_frase4":"¡Maravilloso!",
		"ultima_frase5":"Estoy muy feliz",
		"ultima_frase6":"Me alegró el día",
		"acerto":"Excelente!",
		"valor_a_receber":"Precio del corte",
		"erros_cometidos":"Errores totales",
		"dinheiro_perdido":"Dinero perdido",
		"lucro":"beneficio total",
		"dinheiro_fim_do_dia":"Dinero ganado",
		"despesas":"Gastos",
		"comecar":"Empezar juego",
		"proximo":"Próximo cliente",
		"proximo_dia":"Día siguiente",
		"fundo_jogo":"¡Esta es la escena que puedes decorar!",
		"apresentacao" : "Este es \n tu cliente",
		"instrucao_inicial":"Primero calcula el \n área de la cabeza",
		"explicacao_fita":"Arrastrando la cinta métrica \n para calcular",
		"validando_etapa":"Un buen peluquero necesita \n conozca a su cliente",
		"calcular_area":"Luego calcula el área del corte.",
		"estilizar":"¡Finalmente, haz que el robot sea elegante!",
		"satisfeitos":"Clientes satisfechos",
		"insatisfeitos":"Nuevos intentos",
		"erros":"Errores",
		"dinheiro_total":"Ganancias Totales", ###########################################
		"menu":"Menú",
		"carregar":"Cargar juego",
		"sair":"Abandonar el juego"}
		}
	var create_json = File.new()
	create_json.open("res://JSON_Language/translation.json", File.WRITE) 
	create_json.store_line(to_json(data_to_send))
	print("saved")
	create_json.close()
	# Save data ################################################# Just to create final JSON

