extends Node

func _ready():
	robot_phrases()

func robot_phrases():
	var data_to_send = {
		"en":{"Game_name":"ShapeStylist",
		"saudacao":"Hello friend!",
		"frase_1":"My name is ",
		"possibilidade_nomes":"John",
		"possibilidade_nomes2":"Jose",
		"possibilidade_nomes3":"Jack",
		"possibilidade_nomes4":"Josefino",
		"possibilidade_nomes5":"Alberto",
		"possibilidade_nomes6":"Ronaldo",
		"possibilidade_nomes7":"Richard",
		"possibilidade_nomes8":"Kleyson",
		"possibilidade_nomes9":"Bot1231",
		"possibilidade_nomes10":"#312112",
		"possibilidade_nomes11":"Teofilo",
		"possibilidade_nomes12":"Blake",
		"frase_2":"I like ",
		"possibilidade_gostos":"Sports",
		"possibilidade_gostos2":"Art",
		"possibilidade_gostos3":"Rock",
		"possibilidade_gostos4":"Painting",
		"possibilidade_gostos5":"Sleeping",
		"frase_3":"This is the haircut I want",
		"largura":"width",
		"altura":"height",
		"area":"area",
		"placeholder_resposta":"answer here",
		"placeholder_unidade":"unit here",
		"texto_resultado":"The area is",
		"label_lados":"side",
		"desistir" : "Let's try again!",
		"ultima_frase":"I loved it!",
		"ultima_frase2":"It's awesome!",
		"ultima_frase3":"Really nice!",
		"ultima_frase4":"It's perfect!",
		"ultima_frase5":"I'm really happy",
		"ultima_frase6":"You made my day!",
		"acerto":"Excellent!",
		"valor_a_receber":"Haircut price",
		"erros_cometidos":"Mistakes made",
		"dinheiro_perdido":"Money lost",
		"lucro":"Profit",
		"dinheiro_fim_do_dia":"Earned money",
		"despesas":"Expenses",
		"comecar":"Start Game",
		"proximo":"Next client",
		"proximo_dia":"Next day",
		"satisfeitos":"Satisfied clients",
		"insatisfeitos":"New attempts",
		"erros":"Mistakes",
		"dinheiro_total":"Money earned",
		"menu":"Menu",
		"carregar":"Load Game",
		"sair":"Quit Game",
		"aviso":"!!!WARNING!!!",
		"aviso_mensagem":"Finish the client to save the game or you \n will lose unsaved progress.",
		"continuar":"Continue",
		"botao_proximo":"Next",
		"tutorial_1_0":"Welcome to the tutorial!",
		"tutorial_1_1":"This is the game's scenario. You can decorate it!",
		"tutorial_1_2":"This is your money, you can buy decorations with it.",
		"tutorial_1_3":"Here we have the menu and sound buttons. \n If you want to go back to menu or adjust the sound,\n use those buttons.",
		"tutorial_1_4":"Click next to continue or use the arrows to see any \n information again.",
		"tutorial_2_0":"Here we start to calculate. You'll see \n a colored shape, you need to find it's area.",
		"tutorial_2_1":"Use the measure tape to find the shape's size,\n click the arrow you want to move and drag the tape\n to that side.",
		"tutorial_2_2":"Use the values you got to calculate the area.\n Remember that you need to sum the area of all the\n shapes to get the result.",
		"tutorial_2_3":"Use the virtual keyboard in the game to input your\n answer. Don't forget about the unit!",
		"tutorial_2_4":"Your answer will be shown here. Verify it before\n clicking 'OK' to confirm the answer.",
		"tutorial_2_5":"If you need help, click this button to see some tips",
		"tutorial_2_6":"Click next to see the last part of the tutorial.",
		"tutorial_3_0":"This is the last part of the tutorial, in this stage\n you have more calculations to do.",
		"tutorial_3_1":"Use the values given to calculate the area here,\n just like the last stage.",
		"tutorial_3_2":"Here you have the virtual keyboard too.",
		"tutorial_3_3":"And you have the help button here.",
		"tutorial_3_4":"The next stage you just need to be creative.\n You'll choose a color and how you want the shape\n to fit the robot's head. Then you are done!",
		"tutorial_3_5":"When you are ready you can start the game.\n Have fun!!!"}, 
		
		"es":{"saudacao":"¡Hola amigo!",
		"frase_1":"Mi nombre es ", 
		"possibilidade_nomes":"John",
		"possibilidade_nomes2":"Jose",
		"possibilidade_nomes3":"Jack",
		"possibilidade_nomes4":"Josefino",
		"possibilidade_nomes5":"Alberto",
		"possibilidade_nomes6":"Ronaldo",
		"possibilidade_nomes7":"Richard",
		"possibilidade_nomes8":"Kleyson",
		"possibilidade_nomes9":"Bot1231",
		"possibilidade_nomes10":"#312112",
		"possibilidade_nomes11":"Teofilo",
		"possibilidade_nomes12":"Blake",
		"frase_2":"Me gusta ",
		"possibilidade_gostos":"Desportos",
		"possibilidade_gostos2":"Pintura",
		"possibilidade_gostos3":"Artes",
		"possibilidade_gostos4":"Rock",
		"possibilidade_gostos5":"Dormir",
		"frase_3":"Quiero este corte",
		"largura":"ancho",
		"altura":"altura",
		"area":"área",
		"placeholder_resposta":"responde aquí",
		"placeholder_unidade":"unidad aquí",
		"texto_resultado":"El área es",
		"label_lados":"lado",
		"desistir" : "Intentemos otra vez!",
		"ultima_frase":"¡Yo amé!",
		"ultima_frase2":"¡Esta perfecto!",
		"ultima_frase3":"¡Muy bien!",
		"ultima_frase4":"¡Maravilloso!",
		"ultima_frase5":"Estoy muy feliz",
		"ultima_frase6":"Me alegró el día",
		"acerto":"Excelente!",
		"valor_a_receber":"Precio del corte",
		"erros_cometidos":"Errores totales",
		"dinheiro_perdido":"Dinero perdido",
		"lucro":"beneficio total",
		"dinheiro_fim_do_dia":"Dinero ganado",
		"despesas":"Gastos",
		"comecar":"Empezar juego",
		"proximo":"Próximo cliente",
		"proximo_dia":"Día siguiente",
		"satisfeitos":"Clientes satisfechos",
		"insatisfeitos":"Nuevos intentos",
		"erros":"Errores",
		"dinheiro_total":"Dinero ganado",
		"menu":"Menú",
		"carregar":"Cargar juego",
		"sair":"Abandonar el juego",
		"aviso":"¡¡¡CUIDADO!!!",
		"aviso_mensagem":"Finaliza el cliente para guardar el juego /n o perderás el progreso no guardado.",
		"continuar":"Continuar",
		"botao_proximo":"Siguiente",
		"tutorial_1_0":"¡Bienvenido al tutorial!",
		"tutorial_1_1":"Este es el escenario del juego. ¡Puedes decorarlo!",
		"tutorial_1_2":"Este es tu dinero, puedes comprar adornos con él.",
		"tutorial_1_3":"Aquí tenemos los botones de menú y sonido. \n Si desea volver al menú o ajustar el sonido,\n usa esos botones.",
		"tutorial_1_4":"Haga clic en Siguiente para \n continuar o utilice las flechas para ver cualquiera \n información nuevamente.",
		"tutorial_2_0":"Aquí empezamos a calcular. Verás \n una forma coloreada, necesitas encontrar su área.",
		"tutorial_2_1":"Usa la cinta métrica para encontrar el tamaño de la\n forma, haga clic en la flecha que desea mover y\n arrastre la cinta a ese lado.",
		"tutorial_2_2":"Usa los valores que obtuviste para calcular el área.\n Recuerda que necesitas sumar el área de todos los\n formas para obtener el resultado.",
		"tutorial_2_3":"Usa el teclado virtual del juego para ingresar tu\n respuesta. ¡No te olvides de la unidad!",
		"tutorial_2_4":"Tu respuesta se mostrará aquí. Compruébalo antes\n haciendo clic en 'OK' para confirmar la respuesta.",
		"tutorial_2_5":"Si necesitas ayuda, haz clic en este botón para\n ver algunos consejos.",
		"tutorial_2_6":"Haga clic en siguiente para ver la última parte\n del tutorial.",
		"tutorial_3_0":"Esta es la última parte del tutorial, en esta etapa.\n tienes más cálculos que hacer.",
		"tutorial_3_1":"Utilice los valores dados para calcular el área aquí,\n al igual que la última etapa.",
		"tutorial_3_2":"Aquí tienes también el teclado virtual.",
		"tutorial_3_3":"Y tienes el botón de ayuda aquí.",
		"tutorial_3_4":"La siguiente etapa sólo necesita ser creativo.\n Tú elegirás un color y cómo quieres la forma\n para adaptarse a la cabeza del robot.\n ¡Entonces ya está!",
		"tutorial_3_5":"Cuando estés listo podrás comenzar el juego.\n ¡¡¡Divertirse!!!"}
		}
	var create_json = File.new()
	create_json.open("res://translation.json", File.WRITE) 
	create_json.store_line(to_json(data_to_send))
	print("saved")
	create_json.close()

